### ISSUE TITLE
Failed to activate the scroll-marker package

### ISSUE THREAD

**Issue by griffindavis** [surdu/scroll-marker#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [scroll-marker](https://github.com/surdu/scroll-marker) package 0.3.0

### Stack Trace

Failed to activate the scroll-marker package

```
At Cannot read property 'fontSize' of undefined

TypeError: Cannot read property 'fontSize' of undefined
    at /packages/scroll-marker/lib/Marker.js:7:33)
    at /packages/scroll-marker/lib/Marker.js:51:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/scroll-marker/lib/MarkerLayer.js:4:16)
    at /packages/scroll-marker/lib/MarkerLayer.js:64:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/scroll-marker/lib/MarkerView.js:4:21)
    at /packages/scroll-marker/lib/MarkerView.js:47:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/scroll-marker/lib/api.js:1:181)
    at /packages/scroll-marker/lib/api.js:23:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
```

### Commands

```
```

### Non-Core Packages

```
highlight-selected 0.14.0 
minimap 4.29.9 
scroll-marker 0.3.0 
```

**Comment by surdu** [comment]
Nevermind! Started writing tests and it comes up in tests ;)
